create extension if not exists pgcrypto;

create table if not exists public.venues (
	id uuid primary key default gen_random_uuid(),
	name text not null,
	city text not null,
	capacity integer not null,
	created_at timestamptz not null default now()
);

create table if not exists public.zones (
	id uuid primary key default gen_random_uuid(),
	venue_id uuid not null references public.venues(id) on delete cascade,
	label text not null,
	capacity integer not null
);

create table if not exists public.zone_telemetry (
	id bigint generated by default as identity primary key,
	zone_id uuid not null references public.zones(id) on delete cascade,
	occupancy integer not null,
	recorded_at timestamptz not null default now()
);

create table if not exists public.gates (
	id uuid primary key default gen_random_uuid(),
	venue_id uuid not null references public.venues(id) on delete cascade,
	label text not null
);

create table if not exists public.gate_scans (
	id bigint generated by default as identity primary key,
	gate_id uuid not null references public.gates(id) on delete cascade,
	scan_count integer not null,
	recorded_at timestamptz not null default now()
);

create table if not exists public.sustainability_metrics (
	id bigint generated by default as identity primary key,
	venue_id uuid not null references public.venues(id) on delete cascade,
	metric_type text not null check (metric_type in ('energy_kwh', 'water_l', 'waste_diverted_pct')),
	value numeric not null,
	target numeric not null,
	recorded_at timestamptz not null default now()
);

create table if not exists public.alerts (
	id uuid primary key default gen_random_uuid(),
	venue_id uuid not null references public.venues(id) on delete cascade,
	zone_id uuid references public.zones(id) on delete set null,
	severity text not null check (severity in ('warn', 'critical')),
	message text not null,
	ai_recommendation text not null,
	status text not null default 'open' check (status in ('open', 'handled')),
	created_at timestamptz not null default now(),
	handled_by uuid references auth.users(id) on delete set null,
	handled_at timestamptz
);

create table if not exists public.volunteers (
	id uuid primary key default gen_random_uuid(),
	venue_id uuid not null references public.venues(id) on delete cascade,
	zone_id uuid references public.zones(id) on delete set null,
	name text not null,
	status text not null check (status in ('assigned', 'available'))
);

create table if not exists public.copilot_queries (
	id uuid primary key default gen_random_uuid(),
	user_id uuid not null references auth.users(id) on delete cascade,
	question text not null,
	grounded_data_summary text not null,
	answer text not null,
	created_at timestamptz not null default now()
);

create index if not exists venues_created_at_idx on public.venues (created_at);
create index if not exists zone_telemetry_recorded_at_idx on public.zone_telemetry (recorded_at);
create index if not exists gate_scans_recorded_at_idx on public.gate_scans (recorded_at);
create index if not exists sustainability_metrics_recorded_at_idx on public.sustainability_metrics (recorded_at);
create index if not exists alerts_created_at_idx on public.alerts (created_at);
create index if not exists alerts_zone_id_idx on public.alerts (zone_id);
create index if not exists volunteers_zone_id_idx on public.volunteers (zone_id);
create index if not exists copilot_queries_created_at_idx on public.copilot_queries (created_at);
create index if not exists copilot_queries_user_id_idx on public.copilot_queries (user_id);

alter table public.venues enable row level security;
alter table public.zones enable row level security;
alter table public.zone_telemetry enable row level security;
alter table public.gates enable row level security;
alter table public.gate_scans enable row level security;
alter table public.sustainability_metrics enable row level security;
alter table public.alerts enable row level security;
alter table public.volunteers enable row level security;
alter table public.copilot_queries enable row level security;

create policy "authenticated users can read venues"
on public.venues
for select
to authenticated
using (true);

create policy "authenticated users can read zones"
on public.zones
for select
to authenticated
using (true);

create policy "authenticated users can read zone telemetry"
on public.zone_telemetry
for select
to authenticated
using (true);

create policy "authenticated users can read gates"
on public.gates
for select
to authenticated
using (true);

create policy "authenticated users can read gate scans"
on public.gate_scans
for select
to authenticated
using (true);

create policy "authenticated users can read sustainability metrics"
on public.sustainability_metrics
for select
to authenticated
using (true);

create policy "authenticated users can read alerts"
on public.alerts
for select
to authenticated
using (true);

create policy "authenticated users can read volunteers"
on public.volunteers
for select
to authenticated
using (true);

create policy "ops and admin can update alerts"
on public.alerts
for update
to authenticated
using ((auth.jwt() -> 'user_metadata' ->> 'role') in ('ops_manager', 'admin'))
with check ((auth.jwt() -> 'user_metadata' ->> 'role') in ('ops_manager', 'admin'));

create policy "volunteer coordinators and admin can update volunteers"
on public.volunteers
for update
to authenticated
using ((auth.jwt() -> 'user_metadata' ->> 'role') in ('volunteer_coordinator', 'admin'))
with check ((auth.jwt() -> 'user_metadata' ->> 'role') in ('volunteer_coordinator', 'admin'));

create policy "users can view their own copilot queries"
on public.copilot_queries
for select
to authenticated
using (auth.uid() = user_id);
