begin;

create table if not exists public.telemetry_rollups (
  id bigint generated by default as identity primary key,
  venue_id uuid not null references public.venues(id) on delete cascade,
  zone_id uuid references public.zones(id) on delete cascade,
  gate_id uuid references public.gates(id) on delete cascade,
  metric_type text not null check (metric_type in ('occupancy', 'gate_scans', 'energy_kwh', 'water_l', 'waste_diverted_pct')),
  bucket_start timestamptz not null,
  bucket_end timestamptz not null,
  min_value numeric not null,
  max_value numeric not null,
  average_value numeric not null,
  total_value numeric not null,
  sample_count integer not null check (sample_count > 0),
  created_at timestamptz not null default now(),
  constraint telemetry_rollups_dimension_check check (
    (metric_type = 'occupancy' and zone_id is not null and gate_id is null)
    or (metric_type = 'gate_scans' and gate_id is not null and zone_id is null)
    or (metric_type in ('energy_kwh', 'water_l', 'waste_diverted_pct') and zone_id is null and gate_id is null)
  ),
  unique nulls not distinct (venue_id, zone_id, gate_id, metric_type, bucket_start)
);

create index if not exists telemetry_rollups_venue_bucket_idx
on public.telemetry_rollups (venue_id, bucket_start desc);

alter table public.telemetry_rollups enable row level security;
revoke all on table public.telemetry_rollups from anon;
revoke insert, update, delete on table public.telemetry_rollups from authenticated;
grant select on table public.telemetry_rollups to authenticated;

create policy "users can read authorized telemetry rollups"
on public.telemetry_rollups
for select to authenticated
using (public.has_venue_access(venue_id));

create or replace function public.rollup_telemetry(
  p_rollup_before timestamptz,
  p_raw_retention_cutoff timestamptz,
  p_rollup_retention_cutoff timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  rolled_count integer := 0;
  deleted_raw_count integer := 0;
  deleted_rollup_count integer := 0;
  statement_count integer := 0;
begin
  if p_raw_retention_cutoff >= p_rollup_before
     or p_rollup_retention_cutoff >= p_raw_retention_cutoff then
    raise exception 'Invalid telemetry retention windows';
  end if;

  insert into public.telemetry_rollups (
    venue_id, zone_id, metric_type, bucket_start, bucket_end,
    min_value, max_value, average_value, total_value, sample_count
  )
  select
    zones.venue_id,
    zone_telemetry.zone_id,
    'occupancy',
    date_trunc('hour', zone_telemetry.recorded_at),
    date_trunc('hour', zone_telemetry.recorded_at) + interval '1 hour',
    min(zone_telemetry.occupancy),
    max(zone_telemetry.occupancy),
    avg(zone_telemetry.occupancy),
    sum(zone_telemetry.occupancy),
    count(*)
  from public.zone_telemetry
  join public.zones on zones.id = zone_telemetry.zone_id
  where zone_telemetry.recorded_at < p_rollup_before
    and zone_telemetry.recorded_at >= p_raw_retention_cutoff
  group by zones.venue_id, zone_telemetry.zone_id, date_trunc('hour', zone_telemetry.recorded_at)
  on conflict (venue_id, zone_id, gate_id, metric_type, bucket_start)
  do update set
    bucket_end = excluded.bucket_end,
    min_value = excluded.min_value,
    max_value = excluded.max_value,
    average_value = excluded.average_value,
    total_value = excluded.total_value,
    sample_count = excluded.sample_count;
  get diagnostics rolled_count = row_count;

  insert into public.telemetry_rollups (
    venue_id, gate_id, metric_type, bucket_start, bucket_end,
    min_value, max_value, average_value, total_value, sample_count
  )
  select
    gates.venue_id,
    gate_scans.gate_id,
    'gate_scans',
    date_trunc('hour', gate_scans.recorded_at),
    date_trunc('hour', gate_scans.recorded_at) + interval '1 hour',
    min(gate_scans.scan_count),
    max(gate_scans.scan_count),
    avg(gate_scans.scan_count),
    sum(gate_scans.scan_count),
    count(*)
  from public.gate_scans
  join public.gates on gates.id = gate_scans.gate_id
  where gate_scans.recorded_at < p_rollup_before
    and gate_scans.recorded_at >= p_raw_retention_cutoff
  group by gates.venue_id, gate_scans.gate_id, date_trunc('hour', gate_scans.recorded_at)
  on conflict (venue_id, zone_id, gate_id, metric_type, bucket_start)
  do update set
    bucket_end = excluded.bucket_end,
    min_value = excluded.min_value,
    max_value = excluded.max_value,
    average_value = excluded.average_value,
    total_value = excluded.total_value,
    sample_count = excluded.sample_count;
  get diagnostics statement_count = row_count;
  rolled_count := rolled_count + statement_count;

  insert into public.telemetry_rollups (
    venue_id, metric_type, bucket_start, bucket_end,
    min_value, max_value, average_value, total_value, sample_count
  )
  select
    sustainability_metrics.venue_id,
    sustainability_metrics.metric_type,
    date_trunc('hour', sustainability_metrics.recorded_at),
    date_trunc('hour', sustainability_metrics.recorded_at) + interval '1 hour',
    min(sustainability_metrics.value),
    max(sustainability_metrics.value),
    avg(sustainability_metrics.value),
    sum(sustainability_metrics.value),
    count(*)
  from public.sustainability_metrics
  where sustainability_metrics.recorded_at < p_rollup_before
    and sustainability_metrics.recorded_at >= p_raw_retention_cutoff
  group by sustainability_metrics.venue_id, sustainability_metrics.metric_type, date_trunc('hour', sustainability_metrics.recorded_at)
  on conflict (venue_id, zone_id, gate_id, metric_type, bucket_start)
  do update set
    bucket_end = excluded.bucket_end,
    min_value = excluded.min_value,
    max_value = excluded.max_value,
    average_value = excluded.average_value,
    total_value = excluded.total_value,
    sample_count = excluded.sample_count;
  get diagnostics statement_count = row_count;
  rolled_count := rolled_count + statement_count;

  delete from public.zone_telemetry where recorded_at < p_raw_retention_cutoff;
  get diagnostics statement_count = row_count;
  deleted_raw_count := deleted_raw_count + statement_count;
  delete from public.gate_scans where recorded_at < p_raw_retention_cutoff;
  get diagnostics statement_count = row_count;
  deleted_raw_count := deleted_raw_count + statement_count;
  delete from public.sustainability_metrics where recorded_at < p_raw_retention_cutoff;
  get diagnostics statement_count = row_count;
  deleted_raw_count := deleted_raw_count + statement_count;
  delete from public.telemetry_rollups where bucket_end < p_rollup_retention_cutoff;
  get diagnostics deleted_rollup_count = row_count;

  return jsonb_build_object(
    'rolled', rolled_count,
    'deleted_raw', deleted_raw_count,
    'deleted_rollups', deleted_rollup_count
  );
end;
$$;

revoke all on function public.rollup_telemetry(timestamptz, timestamptz, timestamptz)
from public, anon, authenticated;
grant execute on function public.rollup_telemetry(timestamptz, timestamptz, timestamptz)
to service_role;

commit;
